user_age <- function(bday){
  length(seq.Date(from = as.Date(bday), to = Sys.Date(), by = "year"))-1
}

candidateINFO.df <- tribble(
  ~user_name,           ~name,                      ~age,                     ~origin,                       ~affiliations,                                                                             ~background,                                                                                                                                              ~image_url,
  "@CarlosAmayaR",      "Amaya, Carlos",            user_age("1984-09-17"),   "Socha, Boyacá",               "Partido Alianza Verde, Coalición por la Esperanza",                                       "Governor of Boyacá (2016-2019), Chamber of Representatives of Colombia (2010-2014)",                                                                     "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Carlos_amaya_candidato.jpg/480px-Carlos_amaya_candidato.jpg",
  "@davidbarguil",      "Barguil, David",           user_age("1981-06-23"),   "Cereté, Córdoba",             "Partido Conservador Colombiano",                                                          "Senate of the Republic of Colombia (2018-), Chamber of Representatives of Colombia (2010-2018)",                                                         "https://cdn.forbes.co/2020/07/David-Barguil.png",
  "@RoyBarreras",       "Barreras, Roy Leonardo",   user_age("1963-11-27"),   "Cali, Valle del Cauca",       "Colombia Humana, Partido de la Unión por la Gente, Pacto Histórico Colombia Puede",       "Senate of the Republic of Colombia (2010-), Chamber of Representatives of Colombia (2006-2010)",                                                         "https://cr00.epimg.net/radio/imagenes/2021/02/16/6am_hoy_por_hoy/1613475986_201969_1613476080_noticia_normal_recorte1.jpg",
  "@AlejandroChar",     "Char, Alejandro",          user_age("1966-04-16"),   "Barranquilla, Atlántico",     "Partido Cambio Radical, País de Oportunidades, Coalición Equipo por Colombia",            "Mayor of Barranquilla (2008-2011, 2016-2019), Governor of Atlántico (2003-2004)",                                                                        "https://i1.sndcdn.com/avatars-000143344092-gz0x74-t500x500.jpg",
  "@CristoBustos",      "Cristo, Juan Fernando",    user_age("1964-07-11"),   "Cúcuta, Norte de Santander",  "Partido Liberal, Coalición Centro Esperanza",                                             "Minister of the Interior (2014-2017), Senate of the Republic of Colombia (1998-2014)",                                                                   "http://especiales.semana.com/en-el-nombre-del-padre/imagenes/cristo/cristo-retrato-ficha.jpg",
  "@JCecheverryCol",    "Echeverry, Juan Carlos",   user_age("1962-09-12"),   "Bogotá, DC",                  "Partido Conservador, Coalición Equipo por Colombia",                                      "Minister of Finance and Public Credit (2010-2012), Director of the National Planning Department (1999-2002)",                                            "https://pbs.twimg.com/profile_images/1389663660776247311/T88PfHFv_400x400.jpg",
  "@sergio_fajardo",    "Fajardo, Sergio",          user_age("1956-06-19"),   "Medellín, Antioquia",         "Compromiso Ciudadano, Alianza Social Independiente, Coalición Centro Esperanza",          "Governor of Antioquia (2012-2015), Mayor of Medellín (2004-2007)",                                                                                       "https://miro.medium.com/max/1000/1*MB-YD2pTLgwQntmrFMEHWA.jpeg",
  "@juanmanuelgalan",   "Galán, Juan Manuel",       user_age("1972-07-29"),   "Bogotá, DC",                  "Partido Liberal, Nuevo Liberalismo, Coalición Centro Esperanza",                          "Senate of the Republic of Colombia (2006-2018)",                                                                                                         "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Juan_Manuel_Gal%C3%A1n_Pach%C3%B3n.jpg/800px-Juan_Manuel_Gal%C3%A1n_Pach%C3%B3n.jpg",
  "@agaviriau",         "Gaviria, Alejandro",       user_age("1966-06-25"),   "Santiago, Chile",             "Colombia tiene Futuro, Coalición Centro Esperanza",                                       "Minister of Health and Social Protection (2012-2018)",                                                                                                   "https://upload.wikimedia.org/wikipedia/commons/f/f4/Alejandro_Gaviria.png",
  "@FicoGutierrez",     "Gutiérrez, Federico",      user_age("1974-11-28"),   "Medellín, Antioquia",         "Creemos Colombia, Partido de la Unión por la Gente",                                      "Mayor of Medellín (2016-2019)",                                                                                                                          "https://upload.wikimedia.org/wikipedia/commons/0/0f/Federico_Gutierrez_Zuluaga.png?20211009004648",
  "@ingrodolfohdez",    "Hernández, Rodolfo",       user_age("1945-03-26"),   "Piedecuesta, Santander",      "Lógica, Ética y Estética",                                                                "Mayor of Bucaramanga (2016-2019)",                                                                                                                       "https://caracoltv.brightspotcdn.com/dims4/default/a98bf43/2147483647/strip/true/crop/1000x716+0+0/resize/1000x716!/quality/90/?url=https%3A%2F%2Fcaracol-brightspot.s3-us-west-2.amazonaws.com%2Fassets%2Fbluradio%2Fblu_radio_rodolfo_hernandez_procuraduria.jpg",
  "@aydeelizarazoc",    "Lizarazo, Aydeé",          user_age("1965-02-18"),   "Calarcá, Quindío",            "Movimiento Independiente de Renovación Absoluta (MIRA), Coalición Equipo por Colombia",   "Senate of the Republic of Colombia (2018-)",                                                                                                             "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Fotograf%C3%ADa_Aydee_Lizarazo.jpg/640px-Fotograf%C3%ADa_Aydee_Lizarazo.jpg",
  "@FranciaMarquezM",   "Márquez, Francia",         user_age("1982-12-01"),   "Suárez, Cauca",               "Polo Democrático Alternativo, Pacto Histórico Colombia Puede",                            "None",                                                                                                                                                   "https://ichef.bbci.co.uk/news/640/cpsprodpb/111F/production/_101038340_franciamarquezgoldman.jpg",
  "@EnriquePenalosa",   "Peñalosa, Enrique",        user_age("1954-09-30"),   "Washington, DC",              "Partido de la Unión por la Gente, Coalición Equipo por Colombia",                         "Mayor of Bogotá (2016-2019, 1998-2000), Chamber of Representatives of Colombia (1990-1992)",                                                             "https://pbs.twimg.com/profile_images/1486750036503506948/AVW_c1Aw_400x400.jpg",
  "@Luis_Perez_G",      "Pérez, Luis",              user_age("1951-11-30"),   "Cañasgordas, Antioquia",      "Partido Liberal, Colombia piensa en Grande",                                              "Governor of Antioquia (2016-2020), Mayor of Medellín (2001-2004)",                                                                                       "https://upload.wikimedia.org/wikipedia/commons/3/3f/LuisP.jpg",
  "@petrogustavo",      "Petro, Gustavo",           user_age("1956-04-19"),   "Ciénaga de Oro, Córdoba",     "Colombia Humana, Unión Patriótica",                                                       "Senate of the Republic of Colombia (2018- , 2006-2010), Mayor of Bogotá (2012-2015), Chamber of Representatives of Colombia (1990-1994, 1998-2006)",     "https://upload.wikimedia.org/wikipedia/commons/2/2d/Gustavo_Petro_Mayor_of_Bogota.jpg",
  "@JERobledo",         "Robledo, Jorge Enrique",   user_age("1950-02-11"),   "Ibagué, Tolima",              "Dignidad, Polo Democrático Alternativo, Coalición Centro Esperanza",                      "Senate of the Republic of Colombia (2002-)",                                                                                                             "https://sac.org.co/wp-content/uploads/2021/11/RobledoB.jpg",
  "@JohnMiltonR_",      "Rodríguez, John Milton",   user_age("1969-09-18"),   "Cali, Valle del Cauca",       "Colombia Justa Libres",                                                                   "Senate of the Republic of Colombia (2018-)",                                                                                                             "https://img.lalr.co/cms/2022/02/15173521/COLP_252377-1.jpg?size=sm",
  "@CamiloRomero",      "Romero, Camilo",           user_age("1976-07-17"),   "Ipiales, Nariño",             "Partido Alianza Verde, Pacto Histórico por Colombia",                                     "Governor of Nariño (2016-2019), Senate of the Republic of Colombia (2010-2014)",                                                                         "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Camilo_Romero_%28cropped%29.jpg/800px-Camilo_Romero_%28cropped%29.jpg",
  "@DilianFrancisca",   "Toro, Dilian Francisca",   user_age("1959-01-07"),   "Guacarí, Valle del Cauca",    "Partido de la Unión por la Gente, Coalición Equipo por Colombia",                         "Governor of Valle del Cauca (2016-2019), Senate of the Republic of Colombia (2002-2013)",                                                                "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Dilian_Francisca_Toro_Torres.jpg/640px-Dilian_Francisca_Toro_Torres.jpg",
  "@urianaguariyu",     "Uriana, Arelis",           user_age("1976-02-24"),   "Fonseca, La Guajira",         "Movimiento Alternativo Indígena y Social (MAIS), Pacto Histórico por Colombia",           "None",                                                                                                                                                   "https://cloudfront-us-east-1.images.arcpublishing.com/elespectador/DGYMJFMHJNFLHDL6O7RFZXO5AU.jpg",
  "@velascoluisf",      "Velasco, Luis Fernando",   user_age("1964-10-18"),   "Popayán, Cauca",              "Partido Liberal",                                                                         "Senate of the Republic of Colombia (2006-), Chamber of Representatives of Colombia (1998-2006), Mayor of Popayán (1992-1995)",                           "https://uploads.concordia.net/2018/07/15144200/FOTO-LUIS-FERNANDO-VELASCO-D_0-768x768.jpg",
  "@veranodelarosa",    "Verano, Eduardo",          user_age("1950-10-08"),   "Barranquilla, Atlántico",     "Partido Liberal",                                                                         "Governor of Atlántico (2008-2011, 2016-2019), Minister of Environment (1997-1998)",                                                                      "https://alchetron.com/cdn/eduardo-verano-de-la-rosa-c7444950-c9d3-4b01-8028-5dd4764c370-resize-750.jpeg",
  "@OIZuluaga",         "Zuluaga, Óscar Iván",      user_age("1959-02-03"),   "Pensilvania, Caldas",         "Centro Democrático",                                                                      "Minister of Finance and Public Credit (2007-2010), Senate of the Republic of Colombia (2002-2006), Mayor of Pensilvania (1990-1992)",                    "https://www.portafolio.co/files/article_multimedia/files/crop/uploads/2022/01/11/61dd1d8dac217.r_1641881090117.0-130-1334-1133.jpeg"
 )



dash_directory <- "/Users/carlostorunopaniagua/Documents/GitHub/Colombia-2022-Dashboard/data/"
write_rds(candidateINFO.df, 
          paste0(dash_directory, "candidateINFO.rds"))
